name: Bug Report
description: 问题报告
title: "Bug: "

labels:
  - bug

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: 请简明地描述 bug 的基本信息。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: 请描述如何重现这个行为。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: 请描述正常情况下期望的行为。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots or logs
      description: 请尽量详细提供相关截图或日志等信息。

  - type: input
    attributes:
      label: Platform
      description: 项目运行的聊天平台。
      placeholder: e.g. QQ (Konata)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions
      description: 使用的环境版本。
      placeholder: |
        e.g.
        .NET 6.0.301
        Flandre.Framework v1.0.0
        Flandre.Adapters.Konata v1.0.0-alpha
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: 请描述其他想要补充的信息。
