name: Publish NuGet Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish-core:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Publish Core
        id: publish-core
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: Flandre.Core/Flandre.Core.csproj
          PACKAGE_NAME: Flandre.Core
          VERSION_FILE_PATH: Flandre.Core/Flandre.Core.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: false

      - name: Publish Adapters.Konata
        id: publish-adapter-konata
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: Flandre.Adapters.Konata/Flandre.Adapters.Konata.csproj
          PACKAGE_NAME: Flandre.Adapters.Konata
          VERSION_FILE_PATH: Flandre.Adapters.Konata/Flandre.Adapters.Konata.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: false
