name: Unit Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Test Flandre.Core
        run: |
          dotnet test tests/Flandre.Core.Tests/ --collect:"XPlat Code Coverage" -r code-coverage/
          mv code-coverage/**/coverage.cobertura.xml code-coverage/core.xml

      - name: Test Flandre.Framework
        run: |
          dotnet test tests/Flandre.Framework.Tests/ --collect:"XPlat Code Coverage" -r code-coverage/
          mv code-coverage/**/coverage.cobertura.xml code-coverage/fx.xml

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: code-coverage/core.xml,code-coverage/fx.xml
